### ISSUE TITLE
Detect OS for .NET Core Getting Started

### ISSUE THREAD

**Issue by martinwoodward** [dotnet/dotnet.github.io#16]
For the .NET Core getting started page, be cool if we automatically displayed instructions related to the operating system you are browsing from - i.e. browsing on a Mac, have Mac instructions selected rather than Linux etc.

http://dotnet.github.io/core/getting-started/

/cc @blackdwarf

**Comment by thesmithee** [comment]
@martinwoodward this is a great idea actually, will add ASAP. :)

**Comment by thesmithee** [comment]
OK, PR is in the works. :)
