### ISSUE TITLE
Remove or minimize Mozilla selection on buttons group at Getting Started (Core).

### ISSUE THREAD

**Issue by freexnm** [dotnet/dotnet.github.io#18]
At least for me it looks a bit bad. This black and white rectangle on each button when I push it to see manual.
(Wasn't able to take a pic, but I think it's clear how it looks by default :P)

It's just my opinion. I think it's better when they are highlighted without Moz selection.
![screenshot from 2015-06-26 17 06 50](https://cloud.githubusercontent.com/assets/2807031/8379042/f4b144ba-1c25-11e5-8e8b-55b7d32cb24f.png)

**Comment by thesmithee** [comment]
What version of the browser are you using?

**Comment by freexnm** [comment]
@blackdwarf Firefox 42.0
