### ISSUE TITLE
Getting started guide is missing dependency

### ISSUE THREAD

**Issue by markhuber** [dotnet/dotnet.github.io#51]
When trying to follow the Getting Started guide on dotnet.github.io, I'm getting the following exception

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.IO, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

   at System.Console.WriteLine(String value)
   at HelloWorldSample.Program.Main()
```

I resolved this by adding the following dependency

``` json
"System.IO": "4.0.11-beta-*"
```

I don't believe this is something specific to my system, I will open a pull request for the docs.

**Comment by thesmithee** [comment]
Thanks for the catch! Another issue has been reported as well. The site now actually takes the project.json and Program.cs from githu.com/core/samples repo, so fixed it there.
