### ISSUE TITLE
The official MSI installer is not signed

### ISSUE THREAD

**Issue by bob-devereux-zocdoc** [dotnet/dotnet.github.io#54]
The link on the getting started page downloads an msi that does not have a valid digital signature.  Is that by design?

https://dotnet.github.io/getting-started/
https://dotnetcli.blob.core.windows.net/dotnet/dev/Installers/Latest/dotnet-win-x64.latest.msi

**Comment by thesmithee** [comment]
@bob-devereux-zocdoc we are tracking this in dotnet/cli#304. I will close down this issue since this is more of a CLI toolchain issue than of the core site, if that's OK.

**Comment by bob-devereux-zocdoc** [comment]
Thanks for letting me know!
