### ISSUE TITLE
Weak signature in apt repository

### ISSUE THREAD

**Issue by fsateler** [dotnet/dotnet.github.io#84]
Hi,

The dotnet repository is signed weakly, according to newer (>= 1.2.7)
apt versions. It complains:

```
W: http://apt-mo.trafficmanager.net/repos/dotnet/dists/trusty/InRelease: Signature by key 52E16F86FEE04B979B07E28DB02C46DF417A0893 uses weak digest algorithm (SHA1)
```

It seems your repositories are done with aptly. Unfortunately, aptly
does not appear to offer a configuration option, so you'll need to use
a build that includes the following commit:

https://github.com/smira/aptly/commit/1069458aee25b406c8d5b8c29d37a01b6786d2ef

Hopefully this can be fixed, so that users do not get a scary warning
on apt-get update.

**Comment by chuan** [comment]
Thanks for reporting the issue!

We are aware of the problem. We will probably wait for the aptly official build to include the commit to update our aptly version.

**Comment by chuan** [comment]
We have updated our aptly version. This issue should have been fixed now.

**Comment by fsateler** [comment]
Indeed it is fixed. Thanks!

**Comment by brthor** [comment]
Thanks @chuan !

@blackdwarf who has the power to close issues in this repo? 😄

**Comment by fsateler** [comment]
I can because I opened it :)
