### ISSUE TITLE
Getting started page with Docker option repeats step #2 twice

### ISSUE THREAD

**Issue by adilmughal** [dotnet/dotnet.github.io#87]
If you select **Docker** as your option on [Getting Stated](http://dotnet.github.io/getting-started/) page, it shows steps like 1, 2, 2, 3. Not sure if its intentional or not.

**Comment by svick** [comment]
The new Getting Started page (https://www.microsoft.com/net/core#docker) doesn't show that for me. Should this be closed?

**Comment by adilmughal** [comment]
Yes, the new page doesn't have that issue.
